package br.com.rumocap.levantamento;

import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Palavras que descrevem o tipo de negócio ou o produto ("LANCHONETE", "LOJA",
 * "VENDA DE LARANJA"). Sozinhas, não formam um nome próprio; e dois nomes que
 * só têm essas palavras em comum não são, por isso, o mesmo estabelecimento.
 */
public final class Vocabulario {

    /** Em MAIÚSCULAS, sem acentos. */
    public static final Set<String> GENERICAS = Set.copyOf(List.of((
            "DE DO DA DOS DAS E O A OS AS EM NO NA NOS NAS COM PARA POR AO AOS TIPO SEM NOME DENOMINACAO "
            + "LOJA LOJAS LOJINHA COMERCIO COMERCIAL COMERCIANTE PONTO ESTABELECIMENTO VENDA VENDAS VENDE "
            + "CASA PRODUTOS PRODUTO ARTIGOS GERAL GERAIS DIVERSOS VARIEDADES UTILIDADES MISTA MISTO PEQUENO "
            + "PEQUENA BOX BANCA QUIOSQUE TRAILER FABRICA FABRICACAO INDUSTRIA OFICINA OFICINAS AGRICOLA AGRICOLAS "
            + "AGROPECUARIA AGROPECUARIOS AGRO RACAO RACOES GAS AGUA CARVAO LENHA ADUBO ADUBOS SEMENTES PLANTAS "
            + "FLORES FRUTAS VERDURAS LEGUMES PEIXE PEIXES CAMARAO PAES PAO LEITE QUEIJO OVOS POLPA POLPAS "
            + "REFORMAS REFORMA ALIMENTO ALIMENTOS ALIMENTICIOS ALIMENTACAO TRATOR TRATORES MAQUINAS DOMESTICAS "
            + "SERVICO SERVICOS BAR BARES LANCHONETE LANCHONETES LANCHE LANCHES RESTAURANTE CHURRASCARIA CHURRASCO "
            + "PIZZARIA PIZZA SORVETERIA SORVETE SORVETES ACAI PADARIA PANIFICADORA CONFEITARIA DOCERIA CAFE "
            + "CAFETERIA HAMBURGUERIA ESPETINHO PASTELARIA TAPIOCARIA BOTECO BUTECO BUFFET SUCOS SUCO CANTINA "
            + "COMIDA COMIDAS SELF SERVICE MERCADINHO MERCADO SUPERMERCADO MINIMERCADO MERCEARIA MERCEARIAS ATACADO "
            + "ATACADAO ACOUGUE PEIXARIA FRUTARIA FRUTEIRA HORTIFRUTI QUITANDA BEBIDAS DISTRIBUIDORA CONVENIENCIA "
            + "CONVENIENCIAS FRIGORIFICO FRANGO FRANGOS EMPORIO ARMAZEM FEIRA FARMACIA DROGARIA CLINICA CONSULTORIO "
            + "LABORATORIO ODONTOLOGICO ODONTOLOGIA ODONTO DENTAL DENTISTA OTICA FISIOTERAPIA SALAO BELEZA BARBEARIA "
            + "CABELEIREIRO CABELEIREIRA ESTETICA MANICURE ROUPAS ROUPA CONFECCAO CONFECCOES BOUTIQUE MODAS MODA "
            + "CALCADOS SAPATARIA PERFUMARIA PERFUMES COSMETICOS BIJUTERIAS TECIDOS COSTURA COSTURAS COSTUREIRA "
            + "ATELIE CELULAR CELULARES CELL INFORMATICA ELETRONICA ELETRONICOS ASSISTENCIA TECNICA LAN HOUSE "
            + "PROVEDOR INTERNET CIBER CYBER FUNERARIA ESCRITORIO CONTABILIDADE ADVOCACIA CARTORIO LOTERICA BANCO "
            + "LAVANDERIA GRAFICA COPIADORA XEROX FOTOGRAFIA ACADEMIA AUTOESCOLA IMOBILIARIA HOTEL POUSADA PENSAO "
            + "DORMITORIO VETERINARIA PET SHOP CHAVEIRO RELOJOARIA SAPATEIRO MATERIAL MATERIAIS CONSTRUCAO FERRAGENS "
            + "FERRAGEM MOVELARIA MOVEIS MARCENARIA SERRARIA SERRALHERIA VIDRACARIA OLARIA MADEIREIRA MADEIRAS "
            + "ELETRICA HIDRAULICA TINTAS CERAMICA ELETRODOMESTICOS COLCHOES ESTOFADOS MECANICA MOTO MOTOS CARRO "
            + "CARROS BICICLETA BICICLETAS BICICLETARIA BORRACHARIA LAVA JATO LAVAJATO AUTO PECAS AUTOPECAS "
            + "MOTOPECAS POSTO GASOLINA COMBUSTIVEL COMBUSTIVEIS PNEUS BATERIAS FUNILARIA OLEO TROCA ESTACIONAMENTO "
            + "PAPELARIA LIVRARIA BAZAR BALNEARIO BILHAR SINUCA STORE CENTER PRESENTES COZINHA MARMITARIA MARMITA "
            + "MARMITAS QUENTINHAS QUENTINHA REFEICOES DOCES SALGADOS BOLOS BOLO CARNES CARNE TELHAS TIJOLOS "
            + "CIMENTO AREIA VIDROS ARTESANATO ARTESANATOS BRINQUEDOS MOTOTAXI TAXI TRANSPORTE FRETE FRETES "
            + "MUDANCAS SOM SONORIZACAO EVENTOS FESTAS DECORACAO FLORICULTURA PINTURA SOLDA TORNEARIA REFRIGERACAO "
            + "CONSERTO CONSERTOS MANUTENCAO LAVAGEM DEPOSITO CEREAIS PETISCARIA CHOPERIA ADEGA TABERNA TABACARIA "
            + "ANIMAIS ACESSORIOS IMPORTADOS UTENSILIOS INFANTIL INFANTIS FEMININA FEMININO MASCULINA MASCULINO "
            + "INTIMA INTIMAS ESPORTES ESPORTIVOS ESCOLAR ESCOLARES HIGIENE LIMPEZA EMBALAGENS DESCARTAVEIS PLASTICOS "
            + "ALUMINIO FERRO VELHO RECICLAGEM SUCATA GELO PICOLE PICOLES CHOPP CERVEJA CERVEJAS FRIOS LATICINIOS "
            + "TEMPEROS LARANJA LARANJAS BANANA BANANAS MACAXEIRA MANDIOCA TUCUPI FARINHA PORTOES PORTAO GRADES "
            + "ICE CREAM CAMPO METALURGICA CLUB CLUBE FAZER VEICULOS").split(" ")));

    /** Palavras de locais que não são comércio nem serviço do guia (usadas também para corrigir erros de digitação). */
    public static final Set<String> NAO_COMERCIAIS = Set.copyOf(List.of((
            "IGREJA ASSEMBLEIA CONGREGACAO TEMPLO CAPELA PAROQUIA PAROQUIAL CEMITERIO ESCOLA CRECHE ASSOCIACAO "
            + "SINDICATO COOPERATIVA COMUNITARIO COMUNITARIA ESTADIO GINASIO FARINHEIRA CURRAL GALINHEIRO CHIQUEIRO "
            + "POCILGA GRANJA VIVEIRO APIARIO ESTABULO AVIARIO BANHEIRO BANHEIROS REFEITORIO TERRENO GARAGEM GALPAO "
            + "BARRACAO BARRACA ABRIGO ESTRUTURA ESTUFA SECADOR ORATORIO PLANTACAO PREFEITURA SECRETARIA DELEGACIA "
            + "QUARTEL RESIDENCIA MORADIA ALOJAMENTO ALMOXARIFADO DESATIVADO DESATIVADA FECHADO FECHADA ABANDONADO "
            + "ABANDONADA DESOCUPADO DESOCUPADA INATIVO INATIVA CONSELHO DEFENSORIA PROMOTORIA").split(" ")));

    /** Mesmas palavras genéricas, em minúsculas (para comparar nomes já normalizados). */
    static final Set<String> GENERICAS_MINUSCULAS = GENERICAS.stream()
            .map(palavra -> palavra.toLowerCase(Locale.ROOT))
            .collect(Collectors.toUnmodifiableSet());

    private Vocabulario() {
    }

    /** Palavras conhecidas (genéricas e não comerciais) com 6 letras ou mais, usadas na correção de digitação. */
    public static List<String> paraCorrecao() {
        Set<String> todas = new HashSet<>(GENERICAS);
        todas.addAll(NAO_COMERCIAIS);
        todas.addAll(List.of("ESTABELECIMENTO", "CABELEIREIRO", "CONSULTORIO"));
        return todas.stream().filter(palavra -> palavra.length() >= 6).sorted().toList();
    }
}
