-- =============================================================================
-- RumoCap - estrutura inicial do banco
-- =============================================================================

CREATE TABLE categoria (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    CONSTRAINT uk_categoria_nome UNIQUE (nome)
);

CREATE TABLE estabelecimento (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(120) NOT NULL,
    descricao    VARCHAR(400),
    endereco     VARCHAR(255),
    contato      VARCHAR(500),
    horario      VARCHAR(500),
    latitude     DOUBLE PRECISION,
    longitude    DOUBLE PRECISION,
    imagem       VARCHAR(255),
    categoria_id BIGINT       NOT NULL,

    CONSTRAINT fk_estabelecimento_categoria
        FOREIGN KEY (categoria_id) REFERENCES categoria (id),

    CONSTRAINT ck_estabelecimento_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),

    CONSTRAINT ck_estabelecimento_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),

    -- latitude e longitude são informadas juntas (ou nenhuma das duas)
    CONSTRAINT ck_estabelecimento_coordenadas
        CHECK ((latitude IS NULL AND longitude IS NULL)
            OR (latitude IS NOT NULL AND longitude IS NOT NULL))
);

CREATE INDEX idx_estabelecimento_categoria ON estabelecimento (categoria_id);
