-- =============================================================================
-- RumoCap - levantamento de estabelecimentos em fontes públicas e revisão
--
--  * novos campos de contato (telefone, WhatsApp, site ou rede social);
--  * origem de cada registro (fonte, url_fonte, fonte_id);
--  * situação da revisão administrativa: somente estabelecimentos APROVADOS
--    e ativos aparecem no guia público;
--  * localizacao_validada: a posição no mapa foi conferida pelo administrador;
--  * duplicado_de_id: possível duplicado apontado na importação;
--  * histórico das importações e relatos de "informação incorreta".
--
-- O campo "contato" continua existindo para outros contatos (e-mail, redes).
-- Os registros já existentes foram cadastrados pela administração: ficam
-- aprovados, com a fonte "Cadastro manual".
-- =============================================================================

ALTER TABLE estabelecimento ADD COLUMN telefone VARCHAR(40);
ALTER TABLE estabelecimento ADD COLUMN whatsapp VARCHAR(40);
ALTER TABLE estabelecimento ADD COLUMN site VARCHAR(255);

ALTER TABLE estabelecimento ADD COLUMN fonte VARCHAR(80) DEFAULT 'Cadastro manual' NOT NULL;
ALTER TABLE estabelecimento ADD COLUMN url_fonte VARCHAR(500);
ALTER TABLE estabelecimento ADD COLUMN fonte_id VARCHAR(120);
ALTER TABLE estabelecimento ADD COLUMN tipo_fonte VARCHAR(200);
ALTER TABLE estabelecimento ADD COLUMN dados_fonte VARCHAR(4000);

ALTER TABLE estabelecimento ADD COLUMN situacao VARCHAR(20) DEFAULT 'APROVADO' NOT NULL;
ALTER TABLE estabelecimento ADD COLUMN ativo BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE estabelecimento ADD COLUMN localizacao_validada BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE estabelecimento ADD COLUMN duplicado_de_id BIGINT;
ALTER TABLE estabelecimento ADD COLUMN observacao_revisao VARCHAR(1000);

ALTER TABLE estabelecimento ADD COLUMN criado_em TIMESTAMP WITH TIME ZONE;
ALTER TABLE estabelecimento ADD COLUMN atualizado_em TIMESTAMP WITH TIME ZONE;
ALTER TABLE estabelecimento ADD COLUMN visto_na_fonte_em TIMESTAMP WITH TIME ZONE;
ALTER TABLE estabelecimento ADD COLUMN revisado_em TIMESTAMP WITH TIME ZONE;

UPDATE estabelecimento
   SET criado_em = CURRENT_TIMESTAMP,
       atualizado_em = CURRENT_TIMESTAMP,
       localizacao_validada = CASE WHEN latitude IS NULL THEN FALSE ELSE TRUE END;

-- Um mesmo registro da fonte (ex.: "osm:node/123") nunca vira dois estabelecimentos.
ALTER TABLE estabelecimento ADD CONSTRAINT uk_estabelecimento_fonte_id UNIQUE (fonte_id);

ALTER TABLE estabelecimento ADD CONSTRAINT ck_estabelecimento_situacao
    CHECK (situacao IN ('PENDENTE', 'APROVADO', 'RECUSADO'));

ALTER TABLE estabelecimento ADD CONSTRAINT fk_estabelecimento_duplicado_de
    FOREIGN KEY (duplicado_de_id) REFERENCES estabelecimento (id) ON DELETE SET NULL;

CREATE INDEX idx_estabelecimento_situacao ON estabelecimento (situacao, ativo);

-- -----------------------------------------------------------------------------
-- Histórico das importações (uma linha por execução)
-- -----------------------------------------------------------------------------
CREATE TABLE importacao (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte                 VARCHAR(40)  NOT NULL,
    iniciada_em           TIMESTAMP WITH TIME ZONE NOT NULL,
    concluida_em          TIMESTAMP WITH TIME ZONE,
    situacao              VARCHAR(20)  NOT NULL,
    encontrados           INTEGER DEFAULT 0 NOT NULL,
    novos                 INTEGER DEFAULT 0 NOT NULL,
    atualizados           INTEGER DEFAULT 0 NOT NULL,
    sem_alteracao         INTEGER DEFAULT 0 NOT NULL,
    possiveis_duplicados  INTEGER DEFAULT 0 NOT NULL,
    localizacao_pendente  INTEGER DEFAULT 0 NOT NULL,
    repetidos             INTEGER DEFAULT 0 NOT NULL,
    ja_recusados          INTEGER DEFAULT 0 NOT NULL,
    ignorados             INTEGER DEFAULT 0 NOT NULL,
    detalhes              VARCHAR(2000),
    mensagem              VARCHAR(1000),

    CONSTRAINT ck_importacao_situacao CHECK (situacao IN ('EM_ANDAMENTO', 'CONCLUIDA', 'FALHOU'))
);

CREATE INDEX idx_importacao_fonte ON importacao (fonte, iniciada_em);

-- -----------------------------------------------------------------------------
-- "Informação incorreta?": avisos enviados pelos visitantes do guia
-- -----------------------------------------------------------------------------
CREATE TABLE relato (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estabelecimento_id BIGINT        NOT NULL,
    mensagem           VARCHAR(1000) NOT NULL,
    contato            VARCHAR(120),
    criado_em          TIMESTAMP WITH TIME ZONE NOT NULL,
    resolvido          BOOLEAN DEFAULT FALSE NOT NULL,
    resolvido_em       TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_relato_estabelecimento
        FOREIGN KEY (estabelecimento_id) REFERENCES estabelecimento (id) ON DELETE CASCADE
);

CREATE INDEX idx_relato_estabelecimento ON relato (estabelecimento_id);
